// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi3CUKek4D1K2hLzoJkVec7aAZYByAO5M',
    appId: '1:31162020032:web:453e79b52c48808cc53d25',
    messagingSenderId: '31162020032',
    projectId: 'app-mediclock',
    authDomain: 'app-mediclock.firebaseapp.com',
    storageBucket: 'app-mediclock.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNrO0McBs-8oblu902l7-yL4u47l_toQo',
    appId: '1:31162020032:android:216d3a9d221912a2c53d25',
    messagingSenderId: '31162020032',
    projectId: 'app-mediclock',
    storageBucket: 'app-mediclock.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAluzzO5efXf-OTN491wLJhSQjNIs3V3gQ',
    appId: '1:31162020032:ios:c64204da0b9b79c2c53d25',
    messagingSenderId: '31162020032',
    projectId: 'app-mediclock',
    storageBucket: 'app-mediclock.appspot.com',
    iosBundleId: 'com.example.proyectFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAluzzO5efXf-OTN491wLJhSQjNIs3V3gQ',
    appId: '1:31162020032:ios:c64204da0b9b79c2c53d25',
    messagingSenderId: '31162020032',
    projectId: 'app-mediclock',
    storageBucket: 'app-mediclock.appspot.com',
    iosBundleId: 'com.example.proyectFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi3CUKek4D1K2hLzoJkVec7aAZYByAO5M',
    appId: '1:31162020032:web:b60a1a602251c615c53d25',
    messagingSenderId: '31162020032',
    projectId: 'app-mediclock',
    authDomain: 'app-mediclock.firebaseapp.com',
    storageBucket: 'app-mediclock.appspot.com',
  );

}